### PR TITLE
Provide option to disable verification on login

### PR DESCRIPTION
**Pull request by fridex**
# One-line summary

Provide a new option to disable verification on login

## Description

Provide an option to explicitly turn off verification on login. This is especially useful if cluster certificates are not setup and the user is aware of turning off SSL certificate verification and all the implications turning off cert verification introduces.

## Types of Changes

- New feature (non-breaking change which adds functionality)
- Configuration change

## Tasks
_List of tasks you will do to complete the PR_
  - [ ] Keep PR in a good shape to get it in :)

## Review
_List of tasks the reviewer must do to review the PR_
- [ ] Tests

Fixes: #140

### CODE REVIEW

**Comment by nolar** [comment]
@fridex Sorry, I didn't get it from the PR's description. Can you please clarify how this change is related to SSL cert verification?

The `verify` parameter for `login()` call is used to verify the login: i.e. to make a sample API call to see if the configs/envvars are parsed properly, the token is present, and both TCP connection and HTTP(S) authentication do work (this indeed includes the SSL cert verification implicitly). 

But SSL cert verification in general is not affected by this `verify` parameter.

By disabling this auth verification, the login will pass normally. But the operator will fail on the next call to `GET ...`, `GET ...?watch=true`, and on any other API call. Or do I miss something?

**Comment by fridex** [comment]
> @fridex Sorry, I didn't get it from the PR's description. Can you please clarify how this change is related to SSL cert verification?
> 
> The `verify` parameter for `login()` call is used to verify the login: i.e. to make a sample API call to see if the configs/envvars are parsed properly, the token is present, and both TCP connection and HTTP(S) authentication do work (this indeed includes the SSL cert verification implicitly).
> 
> But SSL cert verification in general is not affected by this `verify` parameter.
> 
> By disabling this auth verification, the login will pass normally. But the operator will fail on the next call to `GET ...`, `GET ...?watch=true`, and on any other API call. Or do I miss something?

@nolar, thanks for the review!

I didn't get implementation actually working on the cluster where I'm testing the code; I ended up with permissions denied on CR (I need to install it).

Looking at the implementation, the patch will not be that straightforward. I checked the verification part based on your comment, the code uses pykube and kubernetes package. 

Enforcing:

```python
    _pykube_cfg.cluster["insecure-skip-tls-verify"] = True
```

In `get_pykube_cfg()` does the trick for me and requests when pykube is used are insecure (I can see related urllib3 warnings and code passes).

However, I'm missing why there is a need to call `verify_client()` in `auth.py` which uses the official kubernetes python package as all the routines (hope I checked them all) use pykube. I found just the following comment in auth.py sources:

https://github.com/zalando-incubator/kopf/blob/700c7d14cd6d83c80f8a0d75bdea6f1dd37c5d14/kopf/clients/auth.py#L40-L41

Based on kubernets-python implementation, the instantiation of API client will need to change to respect modified configuration with `verify_ssl` set to `False`. Not sure how that affects other parts of sources, why was this verification implied?

**Comment by goern** [comment]
fixes https://github.com/zalando-incubator/kopf/issues/140

**Comment by nolar** [comment]
Thanks for you contribution. 

The whole authentication was fully reworked in #226. It now supports multiple credentials and dynamic on-demand re-authentication. 

And the verification is also fully gone — it is now implicitly done by trying the API calls, failing with 401, and triggering the re-authentication inside of the operator life time.

After the changes, I see no reasons to add a global CLI option to disable the SSL verification. First of all, it will be applied to all credentials, even when verification (or absence of it) is expected only on one. Second, it conceptually assumes more and more authentication flags to the Kopf's CLI, while K8s authentication is not the goal of this framework and should not be a big part of the user-facing features.

---

To achieve the desired goal of ignoring the SSL certificate validity, please use `@kopf.on.login()` handlers to produce a `kopf.ConnectionInfo(..., verify=False, ...)` instance.

To make it more simple, [`kopf.login_via_pykube()` and `kopf.login_via_client()`](https://kopf.readthedocs.io/en/latest/authentication/#piggybacking) can be used inside of the handler instead of own config parsing, of which the returned [`ConnectionInfo`](https://kopf.readthedocs.io/en/latest/packages/kopf/#kopf.ConnectionInfo) object can be modified with [`dataclasses.replace(result, verify=False)`](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace).

Few examples can be found here:

* Docs: https://kopf.readthedocs.io/en/latest/authentication/
* Example: https://github.com/zalando-incubator/kopf/blob/master/examples/13-hooks/example.py

Please report any issues with the new custom authentication methods if they do not work as expected.

**Comment by nolar** [comment]
PS: Pre-released as `kopf==0.23rc1`. Not yet a stable release (coming in few days).

**Comment by fridex** [comment]
> Thanks for you contribution.
> 
> The whole authentication was fully reworked in #226. It now supports multiple credentials and dynamic on-demand re-authentication.
> 
> And the verification is also fully gone — it is now implicitly done by trying the API calls, failing with 401, and triggering the re-authentication inside of the operator life time.
> 
> After the changes, I see no reasons to add a global CLI option to disable the SSL verification. First of all, it will be applied to all credentials, even when verification (or absence of it) is expected only on one. Second, it conceptually assumes more and more authentication flags to the Kopf's CLI, while K8s authentication is not the goal of this framework and should not be a big part of the user-facing features.
> 
> To achieve the desired goal of ignoring the SSL certificate validity, please use `@kopf.on.login()` handlers to produce a `kopf.ConnectionInfo(..., verify=False, ...)` instance.
> 
> To make it more simple, [`kopf.login_via_pykube()` and `kopf.login_via_client()`](https://kopf.readthedocs.io/en/latest/authentication/#piggybacking) can be used inside of the handler instead of own config parsing, of which the returned [`ConnectionInfo`](https://kopf.readthedocs.io/en/latest/packages/kopf/#kopf.ConnectionInfo) object can be modified with [`dataclasses.replace(result, verify=False)`](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace).
> 
> Few examples can be found here:
> 
> * Docs: https://kopf.readthedocs.io/en/latest/authentication/
> * Example: https://github.com/zalando-incubator/kopf/blob/master/examples/13-hooks/example.py
> 
> Please report any issues with the new custom authentication methods if they do not work as expected.

@nolar thanks for the info. The described design looks neat! :+1:

**Pull request closed without merging**
